apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller
spec:
  replicas: 5
  selector:
    app: nginx
    environment: test
  template:
    metadata:
      labels:
        app: nginx
        environment: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80