apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init-container
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sleep", "15"]
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8085