apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    name: nginx-service
spec:
  containers:
  - name: nginx-service
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
