apiVersion: v1
kind: Pod
metadata: 
  name: secret-env-pod
  namespace: default 
spec:
  containers:
   - name: nginx-container
     image: nginx:latest
     env:
     - name: PASSWORD_ENV_VAR # Name of env variable
       valueFrom:
         secretKeyRef:
           name: mypassword # Name of secret object
           key: password.txt # Name of key in secret object