apiVersion: v1
kind: Pod
metadata: 
  name: secret-volume-pod
spec:
  volumes:
    - name: mysecretvolume # Name of the volume
      secret:
        secretName: mypassword # name of secret
  containers:
   - name: nginx-container
     image: nginx:latest
     volumeMounts:
        - name: mysecretvolume # Name of the volume 
          mountPath: /etc/password-mounted-path
  